const rows = {
	"writing": [
		["airewrite", "Rewrite the input clearly while preserving meaning."],
		["aipolish", "Polish the input for clarity, flow, and professionalism."],
		["aishorten", "Make the input shorter without losing important meaning."],
		["aiexpand", "Expand the input with useful detail but avoid filler."],
		["aiproofread", "Proofread and correct spelling, punctuation, and grammar."],
		["aigrammar", "Correct grammar and briefly explain the most important fixes."],
		["aiformaltone", "Rewrite the input in a professional formal tone."],
		["aicasualtone", "Rewrite the input in a natural friendly casual tone."],
		["aiparagraph", "Turn the input into well-structured paragraphs."],
		["aibullets", "Turn the input into concise, organized bullet points."],
	],
	"knowledge": [
		["aisummarize", "Summarize the input accurately and concisely."],
		["aikeypoints", "Extract the most important key points from the input."],
		["aiexplain", "Explain the topic clearly with practical examples."],
		["aisimplify", "Simplify the input into easier language without changing facts."],
		["aieli5", "Explain the topic in very simple language suitable for a beginner."],
		["aifaq", "Turn the input into a useful FAQ with answers."],
		["aiflashcards", "Create study flashcards from the input."],
		["aistudyguide", "Create a structured study guide from the input."],
		["ainotes", "Turn the input into clean revision notes."],
		["aiglossary", "Extract important terms and give short definitions."],
	],
	"business": [
		["aibusinessplan", "Create a practical business-plan section from the input."],
		["aiswot", "Create a balanced SWOT analysis from the input."],
		["aiproposal", "Draft a concise professional proposal from the input."],
		["aiexecutivesummary", "Create an executive summary focused on decisions and outcomes."],
		["aibusinesscase", "Create a business case covering need, options, benefits, costs, risks, and recommendation."],
		["airiskregister", "Create a risk register with risk, likelihood, impact, mitigation, and owner suggestions."],
		["aistakeholdermap", "Map likely stakeholders by interest, influence, needs, and engagement approach."],
		["aisop", "Turn the input into a clear standard operating procedure."],
		["aiprocessmap", "Describe the process as ordered steps, decisions, inputs, and outputs."],
		["aidecisionmatrix", "Build a decision matrix with sensible criteria and a transparent recommendation."],
	],
	"marketing": [
		["aiadcopy", "Create persuasive but truthful advertising copy from the input."],
		["aicaption", "Create several strong social-media caption options from the input."],
		["aihashtags", "Suggest relevant, non-spammy hashtags for the input."],
		["aicampaign", "Create a practical marketing campaign plan from the input."],
		["aicontentplan", "Create a content plan with themes, formats, cadence, and goals."],
		["aibrandvoice", "Define or apply a consistent brand voice from the input."],
		["aipersona", "Create a realistic customer persona without inventing sensitive personal data."],
		["aivalueprop", "Create a clear value proposition from the input."],
		["aisalespitch", "Create a concise, credible sales pitch from the input."],
		["aicalltoaction", "Generate strong call-to-action options matched to the input."],
	],
	"sales_service": [
		["aifollowup", "Draft a professional follow-up message based on the input."],
		["aiobjection", "Create respectful responses to the sales objections in the input."],
		["aicrmnote", "Turn the input into a concise CRM interaction note with next steps."],
		["aileadqualify", "Create non-sensitive lead-qualification questions and a qualification summary."],
		["aicustomerservice", "Draft a helpful customer-service response to the input."],
		["airefundreply", "Draft a calm, policy-aware refund response from the input."],
		["aicomplaintreply", "Draft a professional response to a customer complaint."],
		["aiescalation", "Turn the input into a clear escalation note with facts, impact, and requested action."],
		["aitestimonial", "Polish a supplied testimonial without inventing claims."],
		["aicustomerfaq", "Create customer-facing FAQs from the input."],
	],
	"meetings": [
		["aimeetingminutes", "Turn the input into clean meeting minutes with decisions and actions."],
		["aiagenda", "Create a focused meeting agenda from the input."],
		["aiactionitems", "Extract action items with suggested owners and due-date placeholders."],
		["aidecisionlog", "Extract decisions, rationale, owner, and follow-up items."],
		["aistandup", "Turn the input into a concise stand-up update: done, next, blockers."],
		["airetro", "Create a retrospective: what worked, what did not, lessons, actions."],
		["aioneonone", "Create a constructive one-on-one discussion agenda from the input."],
		["aiteamupdate", "Turn the input into a concise team progress update."],
		["aihandover", "Create a thorough handover note with status, risks, contacts, and next actions."],
		["aibrief", "Create a concise working brief with objective, context, requirements, constraints, and deliverables."],
	],
	"education": [
		["ailessonplan", "Create a practical lesson plan from the input, with objectives, activities, assessment, and materials."],
		["aiquizmaker", "Create a varied quiz with answers from the input."],
		["aiexamquestions", "Create balanced assessment questions from the input without copying copyrighted exam content."],
		["aimarkingguide", "Create a marking guide or answer rubric for the supplied task."],
		["airubric", "Create a clear assessment rubric with criteria and performance levels."],
		["aihomework", "Create age-appropriate homework practice from the input."],
		["aiclassactivity", "Create an engaging classroom activity from the input."],
		["ailearningobjectives", "Write measurable learning objectives from the input."],
		["airevisionplan", "Create a realistic revision plan from the input."],
		["aiteacherfeedback", "Draft constructive, specific teacher feedback from the input."],
	],
	"publishing": [
		["aibookoutline", "Create a coherent book outline from the input."],
		["aichapteroutline", "Create a detailed chapter outline from the input."],
		["aiblurb", "Draft a compelling but accurate book blurb from the input."],
		["aibackcover", "Draft back-cover copy from the supplied book information."],
		["aieditorialreview", "Review the input for structure, clarity, consistency, audience fit, and editorial risks."],
		["aicopyedit", "Copy-edit the input while preserving author voice."],
		["aifactcheckplan", "Create a fact-checking checklist for claims in the input; flag what requires external verification."],
		["aicontinuitycheck", "Check the supplied material for internal continuity and consistency problems."],
		["aiageappropriate", "Review the supplied educational material for age-appropriate language, cognitive load, and instructions."],
		["aicurriculummap", "Map supplied content to stated learning goals or curriculum outcomes without inventing standards."],
	],
	"career_hr": [
		["airesume", "Improve a supplied resume/CV using only facts provided by the user."],
		["aicoverletter", "Draft a tailored cover letter using only supplied experience and job information."],
		["aiinterviewquestions", "Create role-relevant interview questions and what strong answers should demonstrate."],
		["aiinterviewprep", "Create an interview preparation plan and practice questions from the input."],
		["aijobdescription", "Draft a clear job description with responsibilities, requirements, and success measures."],
		["aiappraisal", "Draft a balanced employee appraisal from supplied evidence."],
		["aiperformancereview", "Turn supplied performance evidence into constructive review language."],
		["aionboarding", "Create a practical onboarding plan for the role or team described."],
		["aitrainingplan", "Create a skills training plan from the input."],
		["aihiringrubric", "Create a fair, job-related hiring rubric that avoids protected-trait criteria."],
	],
	"productivity": [
		["aiplan", "Turn the input into a practical step-by-step plan."],
		["aitodolist", "Turn the input into an actionable to-do list."],
		["aipriority", "Prioritize the supplied tasks by impact, urgency, dependencies, and effort."],
		["aitimeline", "Create a realistic timeline from the supplied work and constraints."],
		["aiprojectplan", "Create a project plan with scope, workstreams, milestones, owners, risks, and next steps."],
		["aimilestones", "Define sensible milestones and acceptance criteria from the input."],
		["aichecklist", "Turn the input into a practical checklist."],
		["aitemplate", "Create a reusable template for the situation described."],
		["aigoals", "Turn the input into clear measurable goals and next actions."],
		["aiweeklyreview", "Turn the input into a weekly review: wins, unfinished work, lessons, risks, and next-week priorities."],
	],
	"finance_admin": [
		["aibudget", "Create a simple budget structure from the supplied figures and goals; do not invent amounts."],
		["aiexpenseplan", "Organize supplied expenses and suggest practical categories and controls."],
		["aiinvoiceemail", "Draft a professional invoice or payment email from the supplied facts."],
		["aipaymentreminder", "Draft a firm but professional payment reminder from the input."],
		["aifinancialsummary", "Summarize supplied financial information without giving regulated financial advice."],
		["aicostcompare", "Compare supplied cost options transparently and identify assumptions."],
		["aiprofitideas", "Suggest lawful operational ideas that could improve profit or reduce waste."],
		["aipricing", "Create a pricing-analysis framework from supplied costs, market assumptions, and goals."],
		["aiprocurement", "Create a procurement checklist or request based on the input."],
		["aivendorcompare", "Create a vendor-comparison table or narrative from supplied vendor information."],
	],
	"communication": [
		["aiemail", "Draft a clear email from the input."],
		["aiwhatsapp", "Draft a concise WhatsApp message from the input."],
		["aimemo", "Draft a professional internal memo from the input."],
		["ainotice", "Draft a clear formal notice from the input."],
		["aiannouncement", "Draft a concise announcement from the input."],
		["aiapology", "Draft a sincere, accountable apology appropriate to the input."],
		["aithankyou", "Draft a warm, specific thank-you message from the input."],
		["aiinvitation", "Draft an invitation with clear event details from the input."],
		["airemindertext", "Draft a concise reminder message from the input."],
		["aifollowuptext", "Draft a short follow-up text message from the input."],
	],
	"creative": [
		["aistory", "Write an original story based on the input and requested audience."],
		["aipoem", "Write an original poem based on the input; do not imitate living authors."],
		["aislogan", "Generate concise original slogan options from the input."],
		["aitagline", "Generate original tagline options from the input."],
		["ainameideas", "Generate brand, project, product, or event name ideas from the input."],
		["aibrainstorm", "Brainstorm varied, practical ideas around the input."],
		["aiplot", "Develop an original plot outline from the input."],
		["aicharacter", "Create an original fictional character profile from the input."],
		["aidialogue", "Write original dialogue for the supplied fictional situation."],
		["aispeech", "Draft an original speech for the supplied audience, purpose, and tone."],
	],
	"developer": [
		["aicodeexplain", "Explain supplied code clearly and identify important behavior and assumptions."],
		["aidebugplan", "Create a debugging plan from the supplied symptoms and code context."],
		["airefactorplan", "Suggest a safe refactoring plan that preserves behavior."],
		["aitestcases", "Generate useful functional and edge-case tests for the supplied requirements or code."],
		["aiunittestideas", "Suggest unit-test cases and test boundaries for the supplied code."],
		["aiapidesign", "Design a maintainable API contract from the supplied product requirements."],
		["aidatamodel", "Suggest a data model from the supplied requirements and constraints."],
		["aisqlhelp", "Help write or explain ordinary data-management SQL; avoid destructive or unauthorized use."],
		["airegexhelp", "Create or explain a regular expression from the supplied matching requirements."],
		["aigittest", "Suggest a safe Git workflow, branch plan, or commit strategy for the supplied development task."],
	],
	"research": [
		["airesearchquestions", "Turn the topic into focused research questions."],
		["aihypothesis", "Create testable hypotheses from the supplied research context."],
		["ailiteraturereview", "Organize supplied sources or notes into a literature-review structure without inventing citations."],
		["aisourcechecklist", "Create a source-evaluation checklist for the topic."],
		["aicompare", "Compare the supplied options using explicit criteria."],
		["aitradeoffs", "Analyze trade-offs among the supplied options."],
		["aicauseeffect", "Map plausible cause-and-effect relationships while distinguishing evidence from hypotheses."],
		["airootcause", "Create a root-cause analysis from the supplied evidence."],
		["aifivewhys", "Run a careful Five Whys analysis while marking assumptions."],
		["aiscenario", "Create realistic scenarios from the input for planning or training."],
	],
	"personal": [
		["aimealplan", "Create a general meal-planning framework from stated preferences; avoid medical nutrition advice."],
		["aiworkoutplan", "Create a general fitness routine from stated goals and constraints; avoid medical rehabilitation advice."],
		["aitravelplan", "Create a practical travel itinerary from the supplied destination, dates, budget, and preferences."],
		["aishoppinglist", "Create an organized shopping list from the input."],
		["aihabitplan", "Create a realistic habit-building plan from the input."],
		["aijournalprompt", "Generate thoughtful journaling prompts from the input."],
		["aiconversationstarter", "Generate respectful conversation starters for the supplied setting."],
		["aigiftideas", "Suggest gift ideas from the supplied relationship, interests, and budget."],
		["aiaffirmation", "Write grounded, non-clinical affirmations based on the input."],
		["aidecisioncoach", "Help structure a personal decision using goals, options, trade-offs, and next steps without making the decision for the user."],
	],
	"creator_build": [
		["aicreatorbrief", "Turn an idea into a creator brief with goal, audience, core value, constraints, and next action."],
		["aifeaturespec", "Turn a feature idea into a compact product specification with behavior, edge cases, and acceptance checks."],
		["aimvpplan", "Reduce the idea to a realistic minimum viable product with must-have scope, deferred scope, and a first test."],
		["aiproductconcept", "Shape the input into a clear product concept with problem, user, solution, differentiation, and risks."],
		["aiproductstory", "Explain the product idea as a compelling but truthful problem-to-solution story."],
		["ailaunchnotes", "Create concise launch notes covering what changed, why it matters, limitations, and how to try it."],
		["aibuildbrief", "Create a build brief with requirements, architecture notes, milestones, test criteria, and rollback considerations."],
		["aicreatorcheck", "Review a creator project for clarity, usefulness, novelty, scope creep, and next best improvement."],
		["aiproductposition", "Create clear product positioning with target user, problem, category, benefit, proof needed, and alternatives."],
		["airoadmapreview", "Review a supplied roadmap for sequencing, dependencies, risk, unnecessary work, and missing validation."],
	],
	"software_quality": [
		["aibugtriage", "Triage a bug report into symptoms, likely causes, severity, reproduction steps, and next diagnostic action."],
		["aierroranalysis", "Analyze an error message or stack trace and explain the most likely cause, fix, and verification steps."],
		["ailogreview", "Review supplied application logs for patterns, suspicious failures, timing clues, and next debugging checks."],
		["aicodeaudit", "Review supplied code for correctness, maintainability, reliability, input validation, and ordinary security issues."],
		["aiperformanceplan", "Create a performance investigation plan with measurement points, likely bottlenecks, experiments, and success criteria."],
		["aidependencyreview", "Review dependencies for necessity, upgrade risk, compatibility concerns, and simplification opportunities."],
		["aireleasecheck", "Create a release-readiness checklist covering tests, migration, configuration, observability, rollback, and communication."],
		["aideploycheck", "Create a deployment checklist with environment validation, secrets checks, smoke tests, monitoring, and rollback."],
		["aiincidentreview", "Create a blameless incident review from supplied facts: timeline, impact, root cause, contributing factors, and prevention."],
		["airegressionplan", "Create a regression-test plan focused on affected behavior, edge cases, integrations, and previously broken paths."],
	],
	"study_mastery": [
		["aistudysession", "Turn a topic and available time into a focused study session with learn, practice, recall, and review phases."],
		["aimemoryhooks", "Create memorable but accurate memory hooks, mnemonics, or associations for the supplied material."],
		["aipracticequestions", "Generate varied practice questions from supplied material and provide concise answers separately."],
		["aiconceptmap", "Turn supplied material into a text-based concept map showing major ideas and relationships."],
		["ailearningpath", "Create a progressive learning path from fundamentals to practical competence for the stated topic."],
		["aiteachback", "Create a teach-back exercise that helps the learner explain the concept in their own words and reveal gaps."],
		["aistudycheck", "Check supplied notes for missing concepts, unclear explanations, weak examples, and likely revision gaps."],
		["aiexamstrategy", "Create an exam strategy from the stated subject, format, time, and preparation level without encouraging cheating."],
		["aiprogressreview", "Review learning progress from supplied evidence and identify strengths, gaps, and the next study priorities."],
		["aifocusplan", "Create a distraction-aware focus plan for a study or work session with realistic blocks and recovery breaks."],
	],
	"conversation_plus": [
		["aivoicenotereply", "Draft a natural reply suitable for sending as a WhatsApp voice note: conversational, clear, and not over-scripted."],
		["aiconversationreply", "Draft a natural reply to the supplied conversation while matching tone and avoiding unnecessary escalation."],
		["aidifficultmessage", "Draft a calm message for a difficult conversation that is clear, respectful, and firm where needed."],
		["aiboundarymessage", "Draft a respectful boundary-setting message that states the limit, reason if useful, and next step without hostility."],
		["ainegotiationmessage", "Draft a collaborative negotiation message that states interests, constraints, options, and a concrete proposal."],
		["aiclarifymessage", "Draft a short clarification message that resolves ambiguity without sounding accusatory."],
		["aiwhatsappstatus", "Write concise WhatsApp Status caption options from the supplied idea, occasion, or mood."],
		["aigroupannouncement", "Draft a mobile-friendly group announcement with the key information first and a clear action if needed."],
		["aicheckinmessage", "Draft a warm, non-intrusive check-in message suited to the relationship and context supplied."],
		["aifriendlyreply", "Turn the supplied intent into a warm, natural, friendly reply without sounding over-formal."],
	],
	"social_fun": [
		["aiicebreakerpro", "Generate fresh, respectful group icebreakers matched to the supplied audience and vibe."],
		["aihypothetical", "Generate imaginative but safe hypothetical questions for discussion, games, or conversation."],
		["aiwouldyourather", "Generate balanced, fun Would You Rather prompts that avoid dangerous, sexual, or humiliating choices."],
		["aitruthprompt", "Generate safe, non-invasive truth questions suitable for a mixed social group."],
		["aidareprompt", "Generate safe, harmless dares that do not involve danger, humiliation, illegality, or harassment."],
		["aichallengeidea", "Generate friendly mini-challenges with a clear goal, time limit, and simple win condition."],
		["aifunquestion", "Generate interesting, light conversation questions that are easy for a group to answer."],
		["aigroupgameidea", "Invent simple group-game ideas with rules, scoring, duration, and low setup overhead."],
		["aimemeconcept", "Generate original meme concepts or caption setups without reproducing copyrighted meme text verbatim."],
		["aibanterreply", "Create playful, non-cruel banter replies that avoid harassment, protected-trait insults, or escalation."],
	],
	"thinking_tools": [
		["aicounterargument", "Present the strongest reasonable counterarguments to the supplied claim without misrepresenting either side."],
		["aipremortem", "Run a premortem: imagine the plan failed, identify plausible causes, warning signs, and preventive actions."],
		["aidecisiontree", "Turn a decision into a simple text decision tree with key branches, consequences, and information needed."],
		["aiassumptioncheck", "Identify explicit and hidden assumptions in the supplied reasoning and suggest ways to test them."],
		["aievidencecheck", "Separate claims, evidence, inference, and unsupported assertions in the supplied material."],
		["aiblindspots", "Identify plausible blind spots, neglected stakeholders, edge cases, and unintended consequences."],
		["aicriteria", "Derive practical evaluation criteria from the stated goal and explain why each criterion matters."],
		["aioptiongen", "Generate meaningfully different options for the stated problem, including conservative and creative approaches."],
		["aitwosidedview", "Present the strongest arguments and trade-offs on two sides of a disputed non-personal question without forcing a verdict."],
		["aiuncertainty", "Audit uncertainty in the supplied conclusion: what is known, unknown, assumed, sensitive to change, and worth verifying."],
	],
	"life_admin": [
		["aierrandplan", "Organize errands into an efficient sequence based on stated location constraints, urgency, and dependencies."],
		["aidailyplan", "Turn supplied tasks and constraints into a realistic daily plan with priorities and buffer time."],
		["aimorningplan", "Create a practical morning routine from the user's stated goals, available time, and obligations."],
		["aieveningreview", "Create a short end-of-day review covering wins, unfinished work, lessons, and tomorrow's first action."],
		["aipackinglist", "Create an organized packing list from the trip, duration, activities, climate information supplied, and constraints."],
		["aicleaningplan", "Turn a space and available time into a simple cleaning sequence with priorities and stop points."],
		["aiorganizeplan", "Create a decluttering or organization plan that starts small, groups similar items, and defines completion criteria."],
		["aiweeklyreset", "Create a weekly reset routine covering calendar, tasks, environment, preparation, and recovery."],
		["aieventplan", "Create a practical small-event plan with purpose, timeline, roles, supplies, communication, and contingency checks."],
		["aihomeproject", "Break a household project into materials, preparation, steps, safety considerations, budget placeholders, and completion checks."],
	],
	"content_creator": [
		["aihookideas", "Generate varied opening hooks matched to the supplied content topic, platform, and audience without clickbait deception."],
		["aivideooutline", "Create a clear video outline with hook, sections, examples, transitions, and closing action."],
		["aishortscript", "Write a concise short-form video script with natural spoken language and a strong opening."],
		["aithumbnailtext", "Generate short thumbnail-text options that are clear, specific, and not misleading."],
		["aicontentseries", "Turn a topic into a coherent multi-post or multi-video content series with progression and purpose."],
		["aireelidea", "Generate short-form reel ideas with hook, visual beat, core point, and simple call to action."],
		["aitiktokscript", "Write a concise vertical-video script with spoken pacing, visual beats, and a non-deceptive hook."],
		["aiyoutubedesc", "Draft a useful YouTube description from supplied video details without inventing links, timestamps, or claims."],
		["aipostcarousel", "Turn a topic into a slide-by-slide social carousel outline with concise copy and logical flow."],
		["aicommentreply", "Draft respectful creator replies to comments, including appreciative, critical, confused, or skeptical comments."],
	],
	"group_community": [
		["aigroupicebreaker", "Create group-specific icebreakers from the stated community purpose and member vibe."],
		["aigroupchallenge", "Create a safe group challenge with rules, participation options, duration, and a simple completion check."],
		["aiwelcomeidea", "Create fresh ideas for welcoming new members without overwhelming them."],
		["aicelebrationmessage", "Draft a warm group celebration message for an achievement, milestone, birthday, or event using only supplied facts."],
		["aigrouprecap", "Turn supplied group notes into a concise recap with highlights, decisions, actions, and open questions."],
		["aicommunityevent", "Plan a lightweight community activity with objective, format, timing, participation rules, and moderation needs."],
		["aibirthdaymessage", "Draft a warm birthday message in the requested tone without inventing personal facts."],
		["aiawardtitles", "Generate playful, positive award-title ideas for a group without humiliating or targeting members."],
		["aigrouprulesfriendly", "Rewrite group rules into friendly, clear, enforceable language while preserving the actual rules."],
		["aiengagementplan", "Create a sustainable community-engagement plan that avoids spam and gives members reasons to participate."],
	],
	"career_growth": [
		["aiportfolioreview", "Review supplied portfolio content for clarity, evidence of impact, project storytelling, and missing proof."],
		["aiprojectstory", "Turn supplied project facts into a strong problem-action-result portfolio story without inventing achievements."],
		["ailinkedinsummary", "Draft or improve a professional profile summary using only supplied experience and goals."],
		["aiskillgap", "Compare stated current skills with a target role and identify concrete, job-relevant skill gaps."],
		["ailearningroadmap", "Create a career learning roadmap with sequencing, practice projects, evidence of skill, and checkpoints."],
		["aicareeroptions", "Map plausible career directions from supplied interests and skills, explaining trade-offs without deciding for the user."],
		["aijobsearchplan", "Create a realistic job-search plan covering targeting, portfolio, applications, networking, tracking, and iteration."],
		["ainegotiateoffer", "Prepare a respectful compensation or offer negotiation plan based only on supplied facts and priorities."],
		["aiperformancegoals", "Turn responsibilities into measurable performance goals with outcomes, indicators, and review cadence."],
		["ainetworkingmessage", "Draft a concise, respectful networking message with a specific reason for reaching out and no pressure."],
	],
	"idea_lab": [
		["aiwildideas", "Generate bold but plausible ideas across very different directions, then note which assumptions each depends on."],
		["aiconstraintsprint", "Turn constraints into a short creativity sprint that uses the limits as design prompts."],
		["aifeatureprioritize", "Prioritize supplied feature ideas using impact, user value, effort, risk, dependencies, and learning value."],
		["aiprototypeplan", "Create the fastest prototype plan that can test the riskiest assumption with minimal build effort."],
		["aiexperimentdesign", "Design a simple experiment with hypothesis, variable, success metric, sample/observation plan, and interpretation limits."],
		["aiuserstories", "Turn supplied product needs into concise user stories with acceptance notes and edge cases."],
		["aiacceptancecriteria", "Write testable acceptance criteria from a supplied feature or requirement."],
		["aiproductrisks", "Identify product risks across usability, reliability, privacy, cost, adoption, abuse, and operational complexity."],
		["aibetaquestions", "Create useful beta-tester questions that reveal confusion, unmet needs, failures, and perceived value."],
		["aifeedbackanalysis", "Organize supplied user feedback into themes, severity, frequency clues, requests, and actionable follow-up questions."],
	],
	"answer_quality": [
		["aireadability", "Improve readability while preserving meaning, factual content, and the intended audience."],
		["aiclarityscore", "Review text for clarity problems and provide a simple qualitative assessment with the highest-impact fixes."],
		["aiaudiencefit", "Assess whether the supplied content fits the stated audience and suggest specific language, depth, and structure changes."],
		["aifirstdraft", "Turn rough notes into a coherent first draft while preserving uncertainty and placeholders instead of inventing facts."],
		["aisecondpass", "Perform a second-pass edit focused on logic, repetition, weak transitions, unnecessary words, and consistency."],
		["aiconciseedit", "Make the supplied text tighter and more direct while preserving all important meaning."],
		["aiplainenglish", "Rewrite the supplied text in clear plain English without making it childish or inaccurate."],
		["aiexamplemaker", "Create a concrete example that demonstrates the supplied concept without introducing unsupported facts."],
		["aianalogy", "Create a useful analogy for the supplied concept and state where the analogy stops being accurate."],
		["aiquestionimprove", "Rewrite a vague or overloaded question into clearer versions that would produce better answers."],
	],

};

export const AI_FEATURE_CATALOG = Object.fromEntries(
	Object.entries(rows).flatMap(([category, items]) => items.map(([command, instruction]) => [command, { command, category, instruction }])),
);
export const AI_FEATURE_COMMANDS = Object.keys(AI_FEATURE_CATALOG);
export const AI_FEATURE_CATEGORIES = Object.fromEntries(
	Object.entries(rows).map(([category, items]) => [category, items.map(([command]) => command)]),
);
export const getAiFeature = (command) => AI_FEATURE_CATALOG[String(command || "").toLowerCase()] || null;
