const rows = {
	"writing": [
		["airewrite", "Rewrite the input clearly while preserving meaning."],
		["aipolish", "Polish the input for clarity, flow, and professionalism."],
		["aishorten", "Make the input shorter without losing important meaning."],
		["aiexpand", "Expand the input with useful detail but avoid filler."],
		["aiproofread", "Proofread and correct spelling, punctuation, and grammar."],
		["aigrammar", "Correct grammar and briefly explain the most important fixes."],
		["aiformaltone", "Rewrite the input in a professional formal tone."],
		["aicasualtone", "Rewrite the input in a natural friendly casual tone."],
		["aiparagraph", "Turn the input into well-structured paragraphs."],
		["aibullets", "Turn the input into concise, organized bullet points."],
	],
	"knowledge": [
		["aisummarize", "Summarize the input accurately and concisely."],
		["aikeypoints", "Extract the most important key points from the input."],
		["aiexplain", "Explain the topic clearly with practical examples."],
		["aisimplify", "Simplify the input into easier language without changing facts."],
		["aieli5", "Explain the topic in very simple language suitable for a beginner."],
		["aifaq", "Turn the input into a useful FAQ with answers."],
		["aiflashcards", "Create study flashcards from the input."],
		["aistudyguide", "Create a structured study guide from the input."],
		["ainotes", "Turn the input into clean revision notes."],
		["aiglossary", "Extract important terms and give short definitions."],
	],
	"business": [
		["aibusinessplan", "Create a practical business-plan section from the input."],
		["aiswot", "Create a balanced SWOT analysis from the input."],
		["aiproposal", "Draft a concise professional proposal from the input."],
		["aiexecutivesummary", "Create an executive summary focused on decisions and outcomes."],
		["aibusinesscase", "Create a business case covering need, options, benefits, costs, risks, and recommendation."],
		["airiskregister", "Create a risk register with risk, likelihood, impact, mitigation, and owner suggestions."],
		["aistakeholdermap", "Map likely stakeholders by interest, influence, needs, and engagement approach."],
		["aisop", "Turn the input into a clear standard operating procedure."],
		["aiprocessmap", "Describe the process as ordered steps, decisions, inputs, and outputs."],
		["aidecisionmatrix", "Build a decision matrix with sensible criteria and a transparent recommendation."],
	],
	"marketing": [
		["aiadcopy", "Create persuasive but truthful advertising copy from the input."],
		["aicaption", "Create several strong social-media caption options from the input."],
		["aihashtags", "Suggest relevant, non-spammy hashtags for the input."],
		["aicampaign", "Create a practical marketing campaign plan from the input."],
		["aicontentplan", "Create a content plan with themes, formats, cadence, and goals."],
		["aibrandvoice", "Define or apply a consistent brand voice from the input."],
		["aipersona", "Create a realistic customer persona without inventing sensitive personal data."],
		["aivalueprop", "Create a clear value proposition from the input."],
		["aisalespitch", "Create a concise, credible sales pitch from the input."],
		["aicalltoaction", "Generate strong call-to-action options matched to the input."],
	],
	"sales_service": [
		["aifollowup", "Draft a professional follow-up message based on the input."],
		["aiobjection", "Create respectful responses to the sales objections in the input."],
		["aicrmnote", "Turn the input into a concise CRM interaction note with next steps."],
		["aileadqualify", "Create non-sensitive lead-qualification questions and a qualification summary."],
		["aicustomerservice", "Draft a helpful customer-service response to the input."],
		["airefundreply", "Draft a calm, policy-aware refund response from the input."],
		["aicomplaintreply", "Draft a professional response to a customer complaint."],
		["aiescalation", "Turn the input into a clear escalation note with facts, impact, and requested action."],
		["aitestimonial", "Polish a supplied testimonial without inventing claims."],
		["aicustomerfaq", "Create customer-facing FAQs from the input."],
	],
	"meetings": [
		["aimeetingminutes", "Turn the input into clean meeting minutes with decisions and actions."],
		["aiagenda", "Create a focused meeting agenda from the input."],
		["aiactionitems", "Extract action items with suggested owners and due-date placeholders."],
		["aidecisionlog", "Extract decisions, rationale, owner, and follow-up items."],
		["aistandup", "Turn the input into a concise stand-up update: done, next, blockers."],
		["airetro", "Create a retrospective: what worked, what did not, lessons, actions."],
		["aioneonone", "Create a constructive one-on-one discussion agenda from the input."],
		["aiteamupdate", "Turn the input into a concise team progress update."],
		["aihandover", "Create a thorough handover note with status, risks, contacts, and next actions."],
		["aibrief", "Create a concise working brief with objective, context, requirements, constraints, and deliverables."],
	],
	"education": [
		["ailessonplan", "Create a practical lesson plan from the input, with objectives, activities, assessment, and materials."],
		["aiquizmaker", "Create a varied quiz with answers from the input."],
		["aiexamquestions", "Create balanced assessment questions from the input without copying copyrighted exam content."],
		["aimarkingguide", "Create a marking guide or answer rubric for the supplied task."],
		["airubric", "Create a clear assessment rubric with criteria and performance levels."],
		["aihomework", "Create age-appropriate homework practice from the input."],
		["aiclassactivity", "Create an engaging classroom activity from the input."],
		["ailearningobjectives", "Write measurable learning objectives from the input."],
		["airevisionplan", "Create a realistic revision plan from the input."],
		["aiteacherfeedback", "Draft constructive, specific teacher feedback from the input."],
	],
	"publishing": [
		["aibookoutline", "Create a coherent book outline from the input."],
		["aichapteroutline", "Create a detailed chapter outline from the input."],
		["aiblurb", "Draft a compelling but accurate book blurb from the input."],
		["aibackcover", "Draft back-cover copy from the supplied book information."],
		["aieditorialreview", "Review the input for structure, clarity, consistency, audience fit, and editorial risks."],
		["aicopyedit", "Copy-edit the input while preserving author voice."],
		["aifactcheckplan", "Create a fact-checking checklist for claims in the input; flag what requires external verification."],
		["aicontinuitycheck", "Check the supplied material for internal continuity and consistency problems."],
		["aiageappropriate", "Review the supplied educational material for age-appropriate language, cognitive load, and instructions."],
		["aicurriculummap", "Map supplied content to stated learning goals or curriculum outcomes without inventing standards."],
	],
	"career_hr": [
		["airesume", "Improve a supplied resume/CV using only facts provided by the user."],
		["aicoverletter", "Draft a tailored cover letter using only supplied experience and job information."],
		["aiinterviewquestions", "Create role-relevant interview questions and what strong answers should demonstrate."],
		["aiinterviewprep", "Create an interview preparation plan and practice questions from the input."],
		["aijobdescription", "Draft a clear job description with responsibilities, requirements, and success measures."],
		["aiappraisal", "Draft a balanced employee appraisal from supplied evidence."],
		["aiperformancereview", "Turn supplied performance evidence into constructive review language."],
		["aionboarding", "Create a practical onboarding plan for the role or team described."],
		["aitrainingplan", "Create a skills training plan from the input."],
		["aihiringrubric", "Create a fair, job-related hiring rubric that avoids protected-trait criteria."],
	],
	"productivity": [
		["aiplan", "Turn the input into a practical step-by-step plan."],
		["aitodolist", "Turn the input into an actionable to-do list."],
		["aipriority", "Prioritize the supplied tasks by impact, urgency, dependencies, and effort."],
		["aitimeline", "Create a realistic timeline from the supplied work and constraints."],
		["aiprojectplan", "Create a project plan with scope, workstreams, milestones, owners, risks, and next steps."],
		["aimilestones", "Define sensible milestones and acceptance criteria from the input."],
		["aichecklist", "Turn the input into a practical checklist."],
		["aitemplate", "Create a reusable template for the situation described."],
		["aigoals", "Turn the input into clear measurable goals and next actions."],
		["aiweeklyreview", "Turn the input into a weekly review: wins, unfinished work, lessons, risks, and next-week priorities."],
	],
	"finance_admin": [
		["aibudget", "Create a simple budget structure from the supplied figures and goals; do not invent amounts."],
		["aiexpenseplan", "Organize supplied expenses and suggest practical categories and controls."],
		["aiinvoiceemail", "Draft a professional invoice or payment email from the supplied facts."],
		["aipaymentreminder", "Draft a firm but professional payment reminder from the input."],
		["aifinancialsummary", "Summarize supplied financial information without giving regulated financial advice."],
		["aicostcompare", "Compare supplied cost options transparently and identify assumptions."],
		["aiprofitideas", "Suggest lawful operational ideas that could improve profit or reduce waste."],
		["aipricing", "Create a pricing-analysis framework from supplied costs, market assumptions, and goals."],
		["aiprocurement", "Create a procurement checklist or request based on the input."],
		["aivendorcompare", "Create a vendor-comparison table or narrative from supplied vendor information."],
	],
	"communication": [
		["aiemail", "Draft a clear email from the input."],
		["aiwhatsapp", "Draft a concise WhatsApp message from the input."],
		["aimemo", "Draft a professional internal memo from the input."],
		["ainotice", "Draft a clear formal notice from the input."],
		["aiannouncement", "Draft a concise announcement from the input."],
		["aiapology", "Draft a sincere, accountable apology appropriate to the input."],
		["aithankyou", "Draft a warm, specific thank-you message from the input."],
		["aiinvitation", "Draft an invitation with clear event details from the input."],
		["airemindertext", "Draft a concise reminder message from the input."],
		["aifollowuptext", "Draft a short follow-up text message from the input."],
	],
	"creative": [
		["aistory", "Write an original story based on the input and requested audience."],
		["aipoem", "Write an original poem based on the input; do not imitate living authors."],
		["aislogan", "Generate concise original slogan options from the input."],
		["aitagline", "Generate original tagline options from the input."],
		["ainameideas", "Generate brand, project, product, or event name ideas from the input."],
		["aibrainstorm", "Brainstorm varied, practical ideas around the input."],
		["aiplot", "Develop an original plot outline from the input."],
		["aicharacter", "Create an original fictional character profile from the input."],
		["aidialogue", "Write original dialogue for the supplied fictional situation."],
		["aispeech", "Draft an original speech for the supplied audience, purpose, and tone."],
	],
	"developer": [
		["aicodeexplain", "Explain supplied code clearly and identify important behavior and assumptions."],
		["aidebugplan", "Create a debugging plan from the supplied symptoms and code context."],
		["airefactorplan", "Suggest a safe refactoring plan that preserves behavior."],
		["aitestcases", "Generate useful functional and edge-case tests for the supplied requirements or code."],
		["aiunittestideas", "Suggest unit-test cases and test boundaries for the supplied code."],
		["aiapidesign", "Design a maintainable API contract from the supplied product requirements."],
		["aidatamodel", "Suggest a data model from the supplied requirements and constraints."],
		["aisqlhelp", "Help write or explain ordinary data-management SQL; avoid destructive or unauthorized use."],
		["airegexhelp", "Create or explain a regular expression from the supplied matching requirements."],
		["aigittest", "Suggest a safe Git workflow, branch plan, or commit strategy for the supplied development task."],
	],
	"research": [
		["airesearchquestions", "Turn the topic into focused research questions."],
		["aihypothesis", "Create testable hypotheses from the supplied research context."],
		["ailiteraturereview", "Organize supplied sources or notes into a literature-review structure without inventing citations."],
		["aisourcechecklist", "Create a source-evaluation checklist for the topic."],
		["aicompare", "Compare the supplied options using explicit criteria."],
		["aitradeoffs", "Analyze trade-offs among the supplied options."],
		["aicauseeffect", "Map plausible cause-and-effect relationships while distinguishing evidence from hypotheses."],
		["airootcause", "Create a root-cause analysis from the supplied evidence."],
		["aifivewhys", "Run a careful Five Whys analysis while marking assumptions."],
		["aiscenario", "Create realistic scenarios from the input for planning or training."],
	],
	"personal": [
		["aimealplan", "Create a general meal-planning framework from stated preferences; avoid medical nutrition advice."],
		["aiworkoutplan", "Create a general fitness routine from stated goals and constraints; avoid medical rehabilitation advice."],
		["aitravelplan", "Create a practical travel itinerary from the supplied destination, dates, budget, and preferences."],
		["aishoppinglist", "Create an organized shopping list from the input."],
		["aihabitplan", "Create a realistic habit-building plan from the input."],
		["aijournalprompt", "Generate thoughtful journaling prompts from the input."],
		["aiconversationstarter", "Generate respectful conversation starters for the supplied setting."],
		["aigiftideas", "Suggest gift ideas from the supplied relationship, interests, and budget."],
		["aiaffirmation", "Write grounded, non-clinical affirmations based on the input."],
		["aidecisioncoach", "Help structure a personal decision using goals, options, trade-offs, and next steps without making the decision for the user."],
	],
};

export const AI_FEATURE_CATALOG = Object.fromEntries(
	Object.entries(rows).flatMap(([category, items]) => items.map(([command, instruction]) => [command, { command, category, instruction }])),
);
export const AI_FEATURE_COMMANDS = Object.keys(AI_FEATURE_CATALOG);
export const AI_FEATURE_CATEGORIES = Object.fromEntries(
	Object.entries(rows).map(([category, items]) => [category, items.map(([command]) => command)]),
);
export const getAiFeature = (command) => AI_FEATURE_CATALOG[String(command || "").toLowerCase()] || null;
