export const OPERATION_CATEGORIES = Object.freeze([
  'Navigate',
  'Customization',
  'Automation',
  'Activity',
  'Moderation',
  'Community',
])

export const DASHBOARD_OPERATIONS = Object.freeze([
  { id: 'overview', icon: '◫', label: 'Overview', description: 'Live bot summary, health and activity.', category: 'Navigate', to: '/' },
  { id: 'operations', icon: '✦', label: 'Operations Hub', description: 'Search the full Alpha operations catalog.', category: 'Navigate', to: '/operations' },
  { id: 'management', icon: '▦', label: 'Management Suite', description: '40+ safe group controls and shortcuts in one place.', category: 'Navigate', to: '/management' },
  { id: 'customize', icon: '✎', label: 'Customize Alpha', description: 'Avatar, identity, fonts, layout, themes and accessibility.', category: 'Navigate', to: '/customize' },
  { id: 'control-center', icon: '⚡', label: 'Control Center', description: 'Group protection and readiness controls.', category: 'Navigate', to: '/control-center' },
  { id: 'templates', icon: '🧩', label: 'Template Library', description: 'Browse Alpha’s built-in communication templates.', category: 'Navigate', to: '/templates' },
  { id: 'commands', icon: '⌘', label: 'Command Registry', description: 'Search and enable or disable bot commands.', category: 'Navigate', to: '/commands' },
  { id: 'groups', icon: '👥', label: 'Group Manager', description: 'Manage every connected WhatsApp group.', category: 'Navigate', to: '/groups' },
  { id: 'members', icon: '👤', label: 'Member Directory', description: 'Search members and moderation records.', category: 'Navigate', to: '/members' },
  { id: 'analytics', icon: '◒', label: 'Analytics', description: 'Review message and group activity trends.', category: 'Navigate', to: '/analytics' },
  { id: 'dm', icon: '✉', label: 'Direct Message', description: 'Send a direct message from Alpha.', category: 'Navigate', to: '/dm' },
  { id: 'broadcast', icon: '📢', label: 'Safe Broadcast', description: 'Send a controlled message to selected groups.', category: 'Navigate', to: '/broadcast' },
  { id: 'logs', icon: '≡', label: 'Live Logs', description: 'Inspect runtime logs and recent bot events.', category: 'Navigate', to: '/logs' },
  { id: 'health', icon: '♡', label: 'Bot Health', description: 'Inspect uptime, memory and connection health.', category: 'Navigate', to: '/health' },
  { id: 'media', icon: '🎬', label: 'Media Studio', description: 'Manage stickers, media jobs and providers.', category: 'Navigate', to: '/media-studio' },
  { id: 'safe-pack', icon: '🛡', label: 'Safe Pack', description: 'Inspect protection, automations and queue health.', category: 'Navigate', to: '/safe-pack' },
  { id: 'settings', icon: '⚙', label: 'Settings', description: 'Manage deployment and dashboard settings.', category: 'Navigate', to: '/settings' },

  { id: 'custom-avatar', icon: '◎', label: 'Dashboard Avatar', description: 'Upload and crop a custom Alpha dashboard avatar.', category: 'Customization', to: '/customize' },
  { id: 'custom-brand', icon: 'A', label: 'Alpha Identity', description: 'Change display name, tagline, owner badge and workspace label.', category: 'Customization', to: '/customize' },
  { id: 'custom-theme', icon: '◐', label: 'Theme Presets', description: 'Royal, Electric, Obsidian and custom accent combinations.', category: 'Customization', to: '/customize' },
  { id: 'custom-font', icon: 'Aa', label: 'Font Repair', description: 'Use the safe UI font stack and glyph diagnostic.', category: 'Customization', to: '/customize' },
  { id: 'custom-accessibility', icon: '◉', label: 'Accessibility', description: 'Font scale, high contrast and reduced motion.', category: 'Customization', to: '/customize' },
  { id: 'custom-density', icon: '↕', label: 'Dashboard Density', description: 'Compact or comfortable dashboard spacing.', category: 'Customization', to: '/customize' },
  { id: 'custom-startup', icon: '↗', label: 'Startup Page', description: 'Choose which Alpha dashboard opens first.', category: 'Customization', to: '/customize' },
  { id: 'custom-visibility', icon: '◌', label: 'Visibility Controls', description: 'Hide or show metrics, search, status and page labels.', category: 'Customization', to: '/customize' },
  { id: 'custom-export', icon: '⇩', label: 'Export Personalization', description: 'Export the safe dashboard profile as JSON.', category: 'Customization', to: '/customize' },
  { id: 'custom-import', icon: '⇧', label: 'Import Personalization', description: 'Import a sanitized dashboard profile.', category: 'Customization', to: '/customize' },

  { id: 'automation-on', icon: '⚡', label: 'Enable Automation Pack', description: 'Enable the recommended new-group automation set.', category: 'Automation', command: '$automationpack on' },
  { id: 'automation-status', icon: '◉', label: 'Automation Status', description: 'Show current recommended automation state.', category: 'Automation', command: '$automationpack status' },
  { id: 'group-pulse', icon: '📡', label: 'Group Pulse', description: 'Run Alpha’s group-management readiness report.', category: 'Automation', command: '$grouppulse' },
  { id: 'birthday-auto', icon: '🎂', label: 'Birthday Automation', description: 'Enable automatic birthday greetings.', category: 'Automation', command: '$birthdayauto on' },
  { id: 'event-alerts', icon: '📅', label: 'Event Alerts', description: 'Enable milestone reminders for saved events.', category: 'Automation', command: '$eventalerts on' },
  { id: 'morning-auto', icon: '☀', label: 'Morning Greeting', description: 'Enable the scheduled morning message.', category: 'Automation', command: '$morningauto on' },
  { id: 'night-auto', icon: '☾', label: 'Night Greeting', description: 'Enable the scheduled good-night message.', category: 'Automation', command: '$nightauto on' },
  { id: 'group-auto-status', icon: '🕒', label: 'Schedule Status', description: 'Review all group automation times and timezone.', category: 'Automation', command: '$groupauto status' },

  { id: 'count-all', icon: '▦', label: 'Full Activity Count', description: 'Rank the current live group membership.', category: 'Activity', command: '$count' },
  { id: 'count-detail', icon: '≣', label: 'Detailed Activity Count', description: 'Show media and last-activity detail for every current member.', category: 'Activity', command: '$count all' },
  { id: 'count-summary', icon: 'Σ', label: 'Activity Summary', description: 'Show cleanup-oriented activity totals and buckets.', category: 'Activity', command: '$count summary' },
  { id: 'count-zero', icon: '0', label: 'Zero-Message Review', description: 'Show current members with no tracked messages.', category: 'Activity', command: '$count zero' },
  { id: 'count-inactive', icon: '◌', label: 'Inactive Review', description: 'Review the default inactive member set.', category: 'Activity', command: '$count inactive' },
  { id: 'count-min-10', icon: '10', label: 'Below 10 Messages', description: 'Review current members below 10 tracked messages.', category: 'Activity', command: '$count member min 10' },
  { id: 'count-min-20', icon: '20', label: 'Below 20 Messages', description: 'Review current members below 20 tracked messages.', category: 'Activity', command: '$count member min 20' },
  { id: 'count-min-50', icon: '50', label: 'Below 50 Messages', description: 'Review current members below 50 tracked messages.', category: 'Activity', command: '$count member min 50' },
  { id: 'count-30d', icon: '30', label: 'Inactive 30 Days', description: 'Review members proven inactive for 30 days.', category: 'Activity', command: '$countinactive 30d' },
  { id: 'count-60d', icon: '60', label: 'Inactive 60 Days', description: 'Review members proven inactive for 60 days.', category: 'Activity', command: '$countinactive 60d' },
  { id: 'count-120d', icon: '120', label: 'Inactive 120 Days', description: 'Review members proven inactive for 120 days.', category: 'Activity', command: '$countinactive 120d' },
  { id: 'count-low-30d', icon: '↘', label: 'Low Activity + 30 Days', description: 'Review below-20 members whose last tracked activity is older than 30 days.', category: 'Activity', command: '$count inactive 20 30d' },
  { id: 'kick-count', icon: '↗', label: 'Kick Last Count', description: 'Preview removal of the exact last count result.', category: 'Activity', command: '$kickcount' },
  { id: 'mute-count', icon: '🔇', label: 'Mute Last Count', description: 'Preview a 7-day mute for the last count result.', category: 'Activity', command: '$mutecount' },
  { id: 'mute-count-30d', icon: '30', label: 'Mute Last Count 30 Days', description: 'Preview a 30-day mute for the exact last count result.', category: 'Activity', command: '$mutecount 30d' },

  { id: 'danger-help', icon: '⚠', label: 'Danger Actions Guide', description: 'Show safeguarded high-impact admin commands.', category: 'Moderation', command: '$danger' },
  { id: 'kick-inactive-30', icon: '🚪', label: 'Kick 30d Inactive', description: 'Preview removal of proven 30-day inactive members.', category: 'Moderation', command: '$kickinactive 30d' },
  { id: 'kick-inactive', icon: '🚪', label: 'Kick 60d Inactive', description: 'Preview removal of proven 60-day inactive members.', category: 'Moderation', command: '$kickinactive 60d' },
  { id: 'kick-inactive-120', icon: '🚪', label: 'Kick 120d Inactive', description: 'Preview removal of proven 120-day inactive members.', category: 'Moderation', command: '$kickinactive 120d' },
  { id: 'mute-inactive', icon: '🔕', label: 'Mute 60d Inactive', description: 'Preview a mute for proven 60-day inactive members.', category: 'Moderation', command: '$muteinactive 60d' },
  { id: 'mute-inactive-120-30', icon: '🔕', label: 'Mute 120d Inactive for 30d', description: 'Preview a 30-day mute for proven 120-day inactive members.', category: 'Moderation', command: '$muteinactive 120d 30d' },
  { id: 'lock-group', icon: '🔒', label: 'Lock Group', description: 'Preview admin-only posting mode.', category: 'Moderation', command: '$muteall' },
  { id: 'unlock-group', icon: '🔓', label: 'Reopen Group', description: 'Restore normal group messaging.', category: 'Moderation', command: '$unmuteall' },

  { id: 'template-menu', icon: '🧰', label: 'Template Menu', description: 'Show every built-in Alpha template.', category: 'Community', command: '$templates' },
  { id: 'rules-template', icon: '📜', label: 'Rules Template', description: 'Preview the built-in group rules template.', category: 'Community', command: '$template rules' },
  { id: 'welcome-template', icon: '👋', label: 'Welcome Template', description: 'Preview the built-in welcome template.', category: 'Community', command: '$template welcome' },
  { id: 'goodbye-template', icon: '↩', label: 'Goodbye Template', description: 'Preview the built-in goodbye template.', category: 'Community', command: '$template goodbye' },
  { id: 'birthday-template', icon: '🎂', label: 'Birthday Template', description: 'Preview the built-in birthday template.', category: 'Community', command: '$template birthday' },
  { id: 'warning-template', icon: '⚠', label: 'Warning Template', description: 'Preview the detailed warning template.', category: 'Community', command: '$template warning' },
  { id: 'antilink-template', icon: '🔗', label: 'Anti-Link Template', description: 'Preview the Anti-Link warning template.', category: 'Community', command: '$template anti-link' },
  { id: 'antistatus-template', icon: '📵', label: 'Anti-Status Template', description: 'Preview the Status mention warning template.', category: 'Community', command: '$template anti-status' },
  { id: 'antispam-template', icon: '🚨', label: 'Anti-Spam Template', description: 'Preview the spam warning template.', category: 'Community', command: '$template anti-spam' },
  { id: 'muted-template', icon: '🔇', label: 'Mute Template', description: 'Preview the member muted template.', category: 'Community', command: '$template muted' },
  { id: 'announcement-template', icon: '📢', label: 'Announcement Template', description: 'Preview the announcement template.', category: 'Community', command: '$template announcement' },
  { id: 'morning-template', icon: '☀', label: 'Morning Template', description: 'Preview the morning greeting template.', category: 'Community', command: '$template morning' },
  { id: 'night-template', icon: '☾', label: 'Night Template', description: 'Preview the night greeting template.', category: 'Community', command: '$template night' },
  { id: 'poll-template', icon: '☑', label: 'Poll Template', description: 'Preview the group poll template.', category: 'Community', command: '$template poll' },
  { id: 'event-template', icon: '📅', label: 'Event Template', description: 'Preview the group event template.', category: 'Community', command: '$template event' },
  { id: 'game-help', icon: '🎮', label: 'Game Help', description: 'Open Alpha’s game-engine help panel.', category: 'Community', command: '$game help' },
])

export const operationCount = DASHBOARD_OPERATIONS.length
