import { createSafeItem, listSafeItems, updateSafeItem } from "../../../db/safePackData.js";
import { recordGameResult } from "../../../db/gameData.js";
import { cleanSafeText } from "../../../utils/safePack.js";

const tttGames = new Map(); const connectGames = new Map(); const feudGames = new Map();
const targetFrom = (context) => context?.mentionedJid?.[0] || context?.participant || "";
const boardTtt = (cells) => cells.map((x, i) => x || String(i + 1)).reduce((rows, x, i) => { rows[Math.floor(i / 3)] ??= []; rows[Math.floor(i / 3)].push(x); return rows; }, []).map((r) => r.join(" │ ")).join("\n─────────\n");
const tttWinner = (b) => [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].find(([a,c,d]) => b[a] && b[a] === b[c] && b[a] === b[d]);
const connectText = (board) => `1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣7️⃣\n${board.map((row) => row.map((x) => x || "⚪").join("")).join("\n")}`;
const connectWinner = (b, r, c, token) => [[0,1],[1,0],[1,1],[1,-1]].some(([dr, dc]) => { let count = 1; for (const sign of [-1,1]) for (let i = 1; i < 4; i += 1) { const rr = r + dr*i*sign; const cc = c + dc*i*sign; if (b[rr]?.[cc] !== token) break; count += 1; } return count >= 4; });

const FEUD = [
	{ q: "Name something people carry to school", answers: ["book", "bag", "pen", "lunch", "water"] },
	{ q: "Name something found in a kitchen", answers: ["pot", "spoon", "plate", "fridge", "stove"] },
	{ q: "Name a reason someone might be late", answers: ["traffic", "sleep", "bus", "rain", "alarm"] },
	{ q: "Name something people do before bed", answers: ["brush", "pray", "read", "bath", "phone"] },
];

const handler = async (sock, msg, from, args, info) => {
	const { command, senderJid, updateName, extendedMessageOriginal, sendMessageWTyping } = info; const reply = (text, mentions = []) => sendMessageWTyping(from, { text, mentions }, { quoted: msg });
	try {
		if (command === "ttt") { const target = targetFrom(extendedMessageOriginal); if (!target || target === senderJid) return reply("❌ Challenge another member: `ttt @member`. "); if (tttGames.has(from)) return reply("❌ A Tic-Tac-Toe game is already active."); tttGames.set(from, { players: [senderJid, target], names: [updateName, target.split("@")[0]], board: Array(9).fill(""), turn: 0, expires: Date.now() + 10 * 60_000 }); return reply(`❎ *Tic-Tac-Toe*\n${boardTtt(Array(9).fill(""))}\n\n@${senderJid.split("@")[0]} starts with \`tttmove 1\`.`, [senderJid, target]); }
		if (command === "tttmove") { const game = tttGames.get(from); if (!game || game.expires < Date.now()) { tttGames.delete(from); return reply("❌ No active Tic-Tac-Toe game."); } if (game.players[game.turn] !== senderJid) return reply("⏳ It is not your turn."); const cell = Number(args[0]) - 1; if (cell < 0 || cell > 8 || game.board[cell]) return reply("❌ Choose an empty position 1–9."); game.board[cell] = game.turn ? "⭕" : "❌"; const won = tttWinner(game.board); if (won) { tttGames.delete(from); await recordGameResult({ groupJid: from, memberJid: senderJid, name: updateName, game: "ttt", points: 20, won: true, correct: true }); return reply(`🏆 @${senderJid.split("@")[0]} wins!\n\n${boardTtt(game.board)}`, game.players); } if (game.board.every(Boolean)) { tttGames.delete(from); return reply(`🤝 Draw!\n\n${boardTtt(game.board)}`); } game.turn = 1 - game.turn; return reply(`${boardTtt(game.board)}\n\nTurn: @${game.players[game.turn].split("@")[0]}`, game.players); }
		if (command === "connect4") { const target = targetFrom(extendedMessageOriginal); if (!target || target === senderJid) return reply("❌ Challenge another member: `connect4 @member`. "); if (connectGames.has(from)) return reply("❌ A Connect Four game is already active."); const board = Array.from({ length: 6 }, () => Array(7).fill("")); connectGames.set(from, { players: [senderJid, target], board, turn: 0, expires: Date.now() + 15 * 60_000 }); return reply(`🔴 *Connect Four*\n${connectText(board)}\n\n@${senderJid.split("@")[0]} starts with \`drop 1\`.`, [senderJid, target]); }
		if (command === "drop") { const game = connectGames.get(from); if (!game || game.expires < Date.now()) { connectGames.delete(from); return reply("❌ No active Connect Four game."); } if (game.players[game.turn] !== senderJid) return reply("⏳ It is not your turn."); const col = Number(args[0]) - 1; if (col < 0 || col > 6) return reply("❌ Choose column 1–7."); let row = 5; while (row >= 0 && game.board[row][col]) row -= 1; if (row < 0) return reply("❌ That column is full."); const token = game.turn ? "🟡" : "🔴"; game.board[row][col] = token; if (connectWinner(game.board, row, col, token)) { connectGames.delete(from); await recordGameResult({ groupJid: from, memberJid: senderJid, name: updateName, game: "connect4", points: 25, won: true, correct: true }); return reply(`🏆 @${senderJid.split("@")[0]} wins!\n${connectText(game.board)}`, game.players); } if (game.board[0].every(Boolean)) { connectGames.delete(from); return reply(`🤝 Draw!\n${connectText(game.board)}`); } game.turn = 1 - game.turn; return reply(`${connectText(game.board)}\nTurn: @${game.players[game.turn].split("@")[0]}`, game.players); }
		if (["familyfeud", "feudanswer"].includes(command)) { if (command === "familyfeud") { const round = FEUD[Math.floor(Math.random()*FEUD.length)]; feudGames.set(from, { ...round, found: [], expires: Date.now()+5*60_000 }); return reply(`👨‍👩‍👧‍👦 *Family Feud*\n\n${round.q}\n\nAnswer with \`feudanswer <answer>\`.`); } const game = feudGames.get(from); if (!game || game.expires < Date.now()) { feudGames.delete(from); return reply("❌ No active feud round."); } const answer = cleanSafeText(args.join(" "), 60).toLowerCase(); const match = game.answers.find((x) => answer.includes(x) && !game.found.includes(x)); if (!match) return reply("❌ Not on the board—try again."); game.found.push(match); await recordGameResult({ groupJid: from, memberJid: senderJid, name: updateName, game: "familyfeud", points: 5, correct: true }); if (game.found.length === game.answers.length) feudGames.delete(from); return reply(`✅ *${match.toUpperCase()}* is on the board!\nFound: ${game.found.join(", ")}`); }
		if (command === "tournament") { const action = String(args[0] || "status").toLowerCase(); const rows = await listSafeItems(from, "tournament", { status: { $in: ["open", "active"] } }, 5); const active = rows[0]; if (action === "create") { if (active) return reply("❌ A tournament is already open."); const title = cleanSafeText(args.slice(1).join(" "), 80) || "Group Championship"; await createSafeItem({ groupJid: from, type: "tournament", memberJid: senderJid, memberName: updateName, text: title, payload: { players: [{ jid: senderJid, name: updateName }] }, status: "open" }); return reply(`🏆 Tournament created: *${title}*. Join with \`tournament join\`.`); } if (!active) return reply("❌ No open tournament."); if (action === "join") { const players = [...(active.payload.players || []).filter((x) => x.jid !== senderJid), { jid: senderJid, name: updateName }].slice(0,16); await updateSafeItem(from, "tournament", active._id, { payload: { ...active.payload, players } }); return reply(`✅ Joined. Players: *${players.length}/16*.`); } if (action === "start") { if (active.memberJid !== senderJid && !info.isGroupAdmin && !info.isOwner) return reply("❌ Only the creator or an admin can start it."); const players = active.payload.players || []; if (players.length < 2) return reply("❌ At least two players are required."); const shuffled = [...players].sort(() => Math.random()-.5); const matches = []; for (let i=0;i<shuffled.length;i+=2) matches.push([shuffled[i],shuffled[i+1]||null]); await updateSafeItem(from,"tournament",active._id,{ status:"active", payload:{...active.payload,matches,round:1} }); return reply(`🏆 *Round 1*\n${matches.map((m,i)=>`${i+1}. ${m[0].name} vs ${m[1]?.name||"BYE"}`).join("\n")}`); } return reply(`🏆 *${active.text}* — ${active.status}\nPlayers: ${(active.payload.players||[]).map((x)=>x.name).join(", ")}`); }
	} catch (error) { console.error("Strategy games failed:", error.message); return reply(`❌ ${error.message}`); }
};

export default () => ({ cmd: ["ttt", "tttmove", "connect4", "drop", "tournament", "familyfeud", "feudanswer"], desc: "Tic-Tac-Toe, Connect Four, tournaments and Family Feud with points", usage: "ttt @member | connect4 @member | tournament create | familyfeud", handler });

