import { createSafeItem, getSafeSettings, listSafeItems, updateSafeSettings } from "../../../db/safePackData.js";
import { cleanSafeText } from "../../../utils/safePack.js";
import { getGameLeaderboard } from "../../../db/gameData.js";

const handler=async(sock,msg,from,args,info)=>{const{command,senderJid,sendMessageWTyping}=info;const reply=(text)=>sendMessageWTyping(from,{text},{quoted:msg});try{
	if(command==="quizbank"){const action=String(args[0]||"list").toLowerCase();const rows=await listSafeItems(from,"quiz-question",{status:"active"},100);if(action==="list")return reply(rows.length?`🧠 *Custom Quiz Bank* — ${rows.length} questions\n${rows.slice(0,20).map((x,i)=>`${i+1}. ${x.text}`).join("\n")}`:"🧠 Quiz bank is empty.");if(action==="add"){const [question,answer,...options]=args.slice(1).join(" ").split("|").map((x)=>cleanSafeText(x,300));if(!question||!answer)return reply("❌ Usage: `quizbank add question | answer | option 2 | option 3`. ");await createSafeItem({groupJid:from,type:"quiz-question",memberJid:senderJid,text:question,payload:{answer,options:[answer,...options].filter(Boolean).slice(0,6)},status:"active"});return reply("✅ Quiz question added.");}return reply("❌ Use `quizbank add ...` or `quizbank list`.");}
	if(command==="season"){const action=String(args[0]||"status").toLowerCase();const seasons=await listSafeItems(from,"game-season",{},20);const active=seasons.find((x)=>x.status==="active");if(action==="start"){if(active)return reply("❌ A season is already active.");const name=cleanSafeText(args.slice(1).join(" "),80)||`Season ${seasons.length+1}`;await createSafeItem({groupJid:from,type:"game-season",memberJid:senderJid,text:name,payload:{startedAt:new Date()},status:"active"});return reply(`🏆 *${name}* started.`);}if(action==="end"){if(!active)return reply("❌ No active season.");const leaders=await getGameLeaderboard(from,10);const {updateSafeItem}=await import("../../../db/safePackData.js");await updateSafeItem(from,"game-season",active._id,{status:"completed",payload:{...active.payload,endedAt:new Date(),leaders}});return reply(`🏆 *${active.text}* ended. Champion: *${leaders[0]?.name||"No player"}*.`);}return reply(active?`🏆 Active season: *${active.text}*`:"🏆 No active season.");}
	if(command==="seasonhistory"){const seasons=await listSafeItems(from,"game-season",{status:"completed"},20);return reply(seasons.length?`📜 *Season History*\n${seasons.map((x,i)=>`${i+1}. ${x.text} — ${x.payload.leaders?.[0]?.name||"No champion"}`).join("\n")}`:"📜 No completed seasons.");}
	if(command==="gamenight"){const value=String(args[0]||"status").toLowerCase();const settings=await getSafeSettings(from);if(value==="off"){await updateSafeSettings(from,{gameNightEnabled:false});return reply("✅ Scheduled game night disabled.");}if(value==="status")return reply(`🎮 Game night: *${settings.gameNightEnabled?`${settings.gameNightDay} ${settings.gameNightTime}`:"OFF"}*`);const day=args[0];const time=args[1];if(!/^(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)$/i.test(day||"")||!/^([01]\d|2[0-3]):[0-5]\d$/.test(time||""))return reply("❌ Usage: `gamenight Friday 20:00` or `gamenight off`. ");await updateSafeSettings(from,{gameNightEnabled:true,gameNightDay:day,gameNightTime:time});return reply(`✅ Game night set for *${day} ${time}*.`);}
}catch(error){console.error("Safe game admin failed:",error.message);return reply(`❌ ${error.message}`);}};
export default()=>({cmd:["quizbank","season","seasonhistory","gamenight"],desc:"Custom quiz bank, seasons and one weekly game-night schedule",usage:"quizbank add | season start | gamenight Friday 20:00",handler});

